/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.27).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Payment;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2022-05-21T20:07:15.167Z")

@Validated
@Api(value = "v1", description = "the v1 API")
@RequestMapping(value = "/")
public interface V1Api {

    @ApiOperation(value = "Add a new payment", nickname = "addPayment", notes = "Record a new payment", tags={ "Payment", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Payment was created successfully"),
        @ApiResponse(code = 400, message = "Payment could not be created, make sure Payment object is valid"),
        @ApiResponse(code = 500, message = "Payment could not be created, server error try again later") })
    @RequestMapping(value = "/v1/payments",
        produces = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Void> addPayment(@ApiParam(value = "Payment object to create"  )  @Valid @RequestBody Payment body) throws InterruptedException;

}
