version: "3.7"

services:
  microredis:
    networks:
      - microservice_esgi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  redis:
    image: "redis"
    networks:
      - microservice_esgi
networks:
  microservice_esgi:
    name: microservice_esgi
    driver: bridge

